### PR TITLE
Update bootstrap to 4.3

### PR DESCRIPTION
**Pull request by p1mps**

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the PR. Can you capitalize the first letter of your commit message, e.g. `Update` instead of `update`?

**Comment by p1mps** [comment]
> Thanks for the PR. Can you capitalize the first letter of your commit message, e.g. Update instead of update?

Done here 93a2b40abe7af6c9a91fa46227a26201865df0ea

FYI I've updated everything to 4.3, added the correct css/js files from bootstrap and also included jquery which is not included in the bootstrap bundle 👍

**Comment by weavejester** [comment]
Thanks for the update. Can you change "Updated" back to "Update"? For all commits going forward, I'm trying to follow the standard [seven rules](https://chris.beams.io/posts/git-commit/#seven-rules).

**Comment by p1mps** [comment]
> Thanks for the update. Can you change "Updated" back to "Update"? For all commits going forward, I'm trying to follow the standard seven rules.

Done 👍. Sorry I copy pasted the message from this commit c59529a2ff3b7c7c5624cd0edde6633caaaa8ef4

**Pull request merged**
